id: opecha:P000477
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9042
  title: དཔལ་གསང་བའི་སྙིང་པོའི་འགྲེལ་པ་ཕྱོགས་བཅུའི་མུན་སེལ།
  volume:
    bba63c655f3d49e4869717756149659a:
      image_group_id: I1KG9074
      title: Volume 1 of dpal gsang ba'i snying po'i 'grel pa phyogs bcu'i mun sel/
      volume_number: 1
      total_pages: 658
  author: ''
ebook_metadata:
  title: དཔལ་གསང་བའི་སྙིང་པོའི་འགྲེལ་པ་ཕྱོགས་བཅུའི་མུན་སེལ།
  author: ''
  sku: P000477
  cover: cover.jpg
  layers:
  - pagination
