id: P000477
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-16 15:41:57.947900
source_metadata:
  id: bdr:W1KG9042
  title: དཔལ་གསང་བའི་སྙིང་པོའི་འགྲེལ་པ་ཕྱོགས་བཅུའི་མུན་སེལ།
  author: ''
  volumes:
    bba63c655f3d49e4869717756149659a:
      image_group_id: I1KG9074
      title: Volume 1 of dpal gsang ba'i snying po'i 'grel pa phyogs bcu'i mun sel/
      volume_number: 1
      total_pages: 658
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
